package ba.unsa.etf.rpr.business;

import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.Flights;
import ba.unsa.etf.rpr.exceptions.FlightBookingException;

public class FlightsManager {

    public Flights add(Flights flight)throws FlightBookingException{
        if(flight.getId() != 0){
            throw new FlightBookingException("Can't add category with ID. ID is autogenerated");
        }
        try {
            return  DaoFactory.flightsDao().add(flight);
        }catch (FlightBookingException f){
            throw f;
        }
    }

    public void delete(int flightId)throws FlightBookingException{

    }
}