package ba.unsa.etf.rpr.business;

import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.Flights;
import ba.unsa.etf.rpr.domain.Passengers;
import ba.unsa.etf.rpr.exceptions.FlightBookingException;
import java.util.List;

public class PassengersManager {
    public Passengers add(Passengers passengers)throws FlightBookingException{
        if(passengers.getId() != 0){
            throw new FlightBookingException("Can't add category with ID. ID is autogenerated");
        }
        try {
            return  DaoFactory.passengersDao().add(passengers);
        }catch (FlightBookingException p){
            throw p;
        }
    }

    public void delete(int passengerId)throws FlightBookingException{
        try {
            DaoFactory.passengersDao().delete(passengerId);
        }catch(FlightBookingException f){
            if(f.getMessage().contains("FOREIGN KEY")){
                throw new FlightBookingException("Cannot delete category which is related to quotes. First delete related quotes before deleting category.");
            }
            throw f;
        }
    }

    public Passengers update(Passengers passengers)throws FlightBookingException{
        return DaoFactory.passengersDao().update(passengers);
    }

    public List<Passengers> getAll() throws FlightBookingException {
        return DaoFactory.passengersDao().getAll();
    }

    public Passengers getById(int id) throws FlightBookingException {
        return DaoFactory.passengersDao().getById(id);
    }

}
